version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: broker
      POSTGRES_USER: broker
      POSTGRES_PASSWORD: broker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db-data:
